services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: lab22-rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: poridhi
      RABBITMQ_DEFAULT_PASS: poridhi
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - lab22-broker-net

volumes:
  rabbitmq_data:

networks:
  lab22-broker-net:
    name: lab22-broker-net
