services:

  app:
    build: .
    container_name: lab22-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./app/logs:/var/log
    networks:
      - lab22-broker-net
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  lab22-broker-net:
    external: true
    name: lab22-broker-net